markdown:   kramdown
style:  davewhipp
dadospessoais: <i class="fas fa-id-card"></i> CREA-RS#00000 | <i class="fas fa-home"></i> Rua xxx, 000/000 - Porto Alegre - RS - 00000-000<br/><i class="fas fa-mobile-alt"></i> (51)995555555 | <i class="fas fa-envelope"></i> nome@gmail.com | <i class="fab fa-linkedin"></i> https://www.linkedin.com/in/ricardo-olsen/
